receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging: {}

 # loki:
  #  endpoint: "http://loki:3100/loki/api/v1/push"

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [logging]

    traces:
      receivers: [otlp]
      exporters: [logging]
